### ISSUE TITLE
No exe

### ISSUE THREAD

**Issue by Snaphaan** [h4ck-rOOt/Lynda-Decryptor#13]
There's probably a step involved using this application that's not mentioned. Where is the exe? None of the files are recognized as a internal or external command".

I'm no programmer but do these files need to be compiled first?

**Comment by Snaphaan** [comment]
Nermind, found it. Main page there is a link to releases with the latest exe's.

And it works, great stuff. Thank you!!

**Comment by shramee** [comment]
Go to > https://github.com/h4ck-rOOt/Lynda-Decryptor

Then hit `Releases`... Under downloads, download the first zip file...
