### ISSUE TITLE
Human readable filenames?

### ISSUE THREAD

**Issue by chaffinched** [h4ck-rOOt/Lynda-Decryptor#16]
Hi, 

The readme suggests that human readable filenames can be generated from Video2brain files. Should the same be true for Lynda files? They are converting fine for me (using mdomnita's build to fix the 4 file limitation) but the filenames are unchanged.

Maybe I'm missing a step.

**Comment by cczhong11** [comment]
you should use this command
/DB     Search for Database or specify the location on your system
`LyndaDecryptor /D "E:\PATH_TO_COURSES\ldc_dl_courses\COURSE_NUM" /DB "C:\Users\USERNAME\AppData\Local\lynda.com\Lynda.com Desktop App\db.sqlite" /OUT "E:\OUTPUT_PATH"`
To be honest, I got error message after I run this, but you still can try it.
I write a python file to fetch data from db.sqlite to get title and rename the file.

**Comment by chaffinched** [comment]
Thanks cczhong11, for some reason I didn't get that to work the first time round, but it does exactly what it should!
