### ISSUE TITLE
Only 4 videos are being decrypted

### ISSUE THREAD

**Issue by imredorange** [h4ck-rOOt/Lynda-Decryptor#20]
I recently downloaded a whole course and tried to decrypt the videos but only 4 videos were decrypted. I tried to decrypt another course and again, i still got 4 videos only. How do I convert all the videos in one go?

**Comment by Dev-iL** [comment]
Duplicate of https://github.com/h4ck-rOOt/Lynda-Decryptor/issues/8

**Comment by imredorange** [comment]
Thank you very much for pointing me to the right direction! My problem is now solved. Again thank you!

**Comment by Dev-iL** [comment]
You're welcome :) 
**PROTIP:** Always look/search in the closed issues section before opening a new one ;)
