### ISSUE TITLE
Getting encrypted .mp4 files through mac desktop app

### ISSUE THREAD

**Issue by jgmaster** [h4ck-rOOt/Lynda-Decryptor#28]
Guys, is .mp4 the new format being used? All I've done was changing the download folder in the application's preferences. The videos are in a directory called "videos" inside my downloads folder normally identified with their respective SHAs followed by the .mp4 extension and, of course, encrypted. Since I don't want to mess with Visual Studio and I've been postponing it for some time, I'm installing Windows via Bootcamp on my Mac. Is the decryptor supposed to work with the .mp4 files?

**Comment by revolutionized** [comment]
You closed and opened and closed again. Did you find a solution?
