### ISSUE TITLE
Decrypting not actually doing anything

### ISSUE THREAD

**Issue by tearsofdeath** [h4ck-rOOt/Lynda-Decryptor#29]
@h4ck-rOOt 

http://prntscr.com/f21np0

the process starts but nothing actually happens. Here's a screenshot of my linda file path to make sure im doing that correctly. http://prntscr.com/f21p79.  Also they are .lynda files

I would really appreciate anyone who could help me, thanks alot for reading.

**Comment by prapeepkc** [comment]
try running with admin privilege in command prompt

**Comment by tearsofdeath** [comment]
fixed it, you have to isolate the files first
