### ISSUE TITLE
Crash when CourseTitle is null @SQLite

### ISSUE THREAD

**Issue by Dev-iL** [h4ck-rOOt/Lynda-Decryptor#3]
The following line throws an exception, because it expects to find a `String` but finds `(null)` instead:

```
var courseTitle = reader.GetString(reader.GetOrdinal("CourseTitle"));
```

This happens for some older courses. There should be a fallback that goes to the `Course` table and `SELECT`s the `Title` field `WHERE ID` is the courseId.

**Comment by h4ck-rOOt** [comment]
This error was fixed in the last merge request.
Thanks for reporting this.
