### ISSUE TITLE
/RM option doesn't remove .caption files

### ISSUE THREAD

**Issue by Dev-iL** [h4ck-rOOt/Lynda-Decryptor#36]
Tested on Windows 10 using commit https://github.com/h4ck-rOOt/Lynda-Decryptor/commit/65ee16a1f77507f7e26c6fced9b435d40989fa31.

**Comment by DmitriySokhach** [comment]
Could you provide name of the course to test please.

**Comment by Dev-iL** [comment]
It's not a matter of a specific course, this was just not an implemented feature at the time of opening (probably still is).

Try it on any course you like.

**Comment by DmitriySokhach** [comment]
I do not have any *.caption files in "offline" folder. Probably Win10 app doesn't store them anymore?
/RM option removes only files that were decrypted, course and author thumbnails are remained in source folder.

**Comment by Dev-iL** [comment]
Just to clarify: this issue does not talk about the lynda version that produces `.ldcw` files.

**Comment by DmitriySokhach** [comment]
Also tried with Wi-Fi turned OFF (top picture) and ON (bottom picture). Used the same video. Seems like subtitles now being downloaded over internet.
![image](https://user-images.githubusercontent.com/2741620/36946412-ee5dd676-1fbc-11e8-9236-9c5733e2469e.png)

**Comment by DmitriySokhach** [comment]
@Dev-iL  thanks for clarification. I didn't know there were more than 1 desktop app.

**Comment by DmitriySokhach** [comment]
made PR on this: #42 
link to commit: https://github.com/h4ck-rOOt/Lynda-Decryptor/pull/42/commits/7470fe2190bfa26c91db9f4f0ebdbf6da1b20bc5

**Comment by Dev-iL** [comment]
Closing since PR was merged.
