### ISSUE TITLE
No subtitles?

### ISSUE THREAD

**Issue by Ryan147** [h4ck-rOOt/Lynda-Decryptor#50]
Hi,

Using the latest binary, when converting I see the videos being saved but not the subtitles from the captions.

Using the tool mdomnita gives the SRT files but still with the cryptic filenames.

**Comment by rosetinted** [comment]
The latest binary is quite out-of-date. You can find a more recent version [here](https://github.com/rosetinted/Lynda-Decryptor/releases/tag/1.5.5).

**Comment by Ryan147** [comment]
Thanks a lot for the reply! New version works as a charm.
