### ISSUE TITLE
decryption methodology

### ISSUE THREAD

**Issue by kqvanity** [h4ck-rOOt/Lynda-Decryptor#62]
Hello,
This is not an issue, but couldn't find any other communication method to reach out. I was wondering how did you come to understand the way the file are encrypted. Is there any systematic methodology for it?
Thanks.

**Comment by Dev-iL** [comment]
In short, the app was written in C# (.NET), so the way it was compiled (using an "intermediate language", or IL) allows, in cases such as this, to recover the source code almost fully (see e.g. ILSpy). The encryption key and algorithm could then be found fairly easily after a bit of digging through the "disassembled" code, and then it was a straightforward matter of implementing the associated decryption process.

**Comment by kqvanity** [comment]
Oh. Thanks for your time!
