### ISSUE TITLE
4 files limit

### ISSUE THREAD

**Issue by plutonian2016** [h4ck-rOOt/Lynda-Decryptor#8]
great job m8!

It works just fine but it won't decrypt more than 4 files in a row. 

I used command line with windows .exe:

LyndaDecryptor /D "K:\Linda Courses\ldc_dl_courses\417082"

and it returns:

K:\Lynda_v1.2>LyndaDecryptor /D "K:\Linda Courses\ldc_dl_courses\417082"
[ARGS] Changing mode to Folder decryption!
[START] Init Decryptor...
[START] Decryptor successful initalized!

[DEC] Decrypting file 438808_f2caf0365368d407180e5bd354c0f945.lynda...
[DEC] Decrypting file 438807_83218ac34c1834c26781fe4bde918ee4.lynda...
[DEC] File decryption completed: K:\Linda Courses\ldc_dl_courses\417082\438808_f
2caf0365368d407180e5bd354c0f945.mp4
[DEC] Decrypting file 438809_b37c2c183d5a4009e0a54324a407a534.lynda...

Press any key to exit the program...
[DEC] File decryption completed: K:\Linda Courses\ldc_dl_courses\417082\438809_b
37c2c183d5a4009e0a54324a407a534.mp4
[DEC] File decryption completed: K:\Linda Courses\ldc_dl_courses\417082\438807_8
3218ac34c1834c26781fe4bde918ee4.mp4
[DEC] Decrypting file 438811_7515ffcc2fe807400fcb273c96ae8cc6.lynda...
[DEC] File decryption completed: K:\Linda Courses\ldc_dl_courses\417082\438811_7
515ffcc2fe807400fcb273c96ae8cc6.mp4

then it is hanging, cursor is blinking.
on click it aborts

**Comment by plutonian2016** [comment]
also, you hardcoded 
"video2brain Desktop App"
while it is actually:
"Lynda.com Desktop App"
C:\Users\<user>\AppData\Local\lynda.com\Lynda.com Desktop App
which also leads to an error while trying to use /DB option

K:\Lynda_v1.2>LyndaDecryptor /D "K:\Linda Courses\ldc_dl_courses\417082" /db
[ARGS] Changing mode to Folder decryption!
[START] Init Decryptor...
[START] Decryptor successful initalized!

[DB] Creating db connection...
[START] Error occured: Could not find a part of the path 'C:\Users\1\AppData\Loc
al\lynda.com\video2brain Desktop App'.

**Comment by ktsarlz** [comment]
I'm also having this issue and still haven't found a solution

**Comment by DaveLampton** [comment]
@h4ck-rOOt, Thnx for creating this!

I'm having the same problem, in Directory decryption mode it gets through only the first four files then it just hangs. When I try to encode any one of the remaining files using File decryption mode, it immediately exits with the error:

`[START] Error occured: Index was outside the bounds of the array.`

...followed by the usage instructions.

**Comment by h4ck-rOOt** [comment]
@plutonian2016 thx man
The app was developed to decrypt files downloaded by Video2Brain Desktop App, so i personally don't own a Lynda.com Account or even using the Lynda.com Desktop App.

Feel free to edit the path in [Program.cs](https://github.com/h4ck-rOOt/Lynda-Decryptor/blob/master/LyndaDecryptor/Program.cs#L157) or combine them to support Lynda.com Desktop App. All you have to do is replacing the hardcoded path on this line with your path. I'm going to support both versions, now that i know the path to this app.

So theres a technique called semaphore i've used to program this app and it seems this is the culprit of all error hanging after 4 files. This issue needs more investigation from my side.

Maybe you can debug this behavior in VS2015?

**Comment by h4ck-rOOt** [comment]
@DaveLampton just hang in, im going to investigate the strange behavior next week...

**Comment by mdomnita** [comment]
The binaries available here  have the 4 file limit, happened to me too. But when I compiled the project from Visual Studio, the compiled one worked just fine. Probably it was a bug when the binaries available here on github were compiled?

**Comment by ktsarlz** [comment]
@mdomnita Can you post or link me to a working version? If that's okay with you. I cant really compile the build I dont have vs 2015, only vs 2008

**Comment by mdomnita** [comment]
There is one in one of the other topics saw it earlier. I can only give you
one in the afternoon (6 hrs from now or so).

On Nov 10, 2016 10:45 AM, "Kobi" <notifications@github.com> wrote:
>
> @mdomnita Can you post or link me to a working version? If that's okay
with you. I cant really compile the build I dont have vs 2015, only vs 2008

**Comment by ktsarlz** [comment]
@mdomnita Yah, saw that one. Tried that one but it didn't worked for me,

**Comment by mdomnita** [comment]
Then I will build one in the afternoon/evening and post it. I only have all stuff at home and I don't have access to it until then.

**Comment by ktsarlz** [comment]
@mdomnita Thanks for that! I will be patiently waiting.

**Comment by mdomnita** [comment]
https://goo.gl/iKiGM2 try this. Just unpack, go to the folder and run 
LyndaDecryptor.exe /D <coursedirectory>

**Comment by ktsarlz** [comment]
@mdomnita Tried this on one of the courses I have. It now works!! Thank you! Hope @h4ck-rOOt will make this to work with the master and hopefully will be able to convert .captions to .srt

**Comment by ZerocoolZa** [comment]
dude you the best. what not make a gui for it then u would be the master , im not sure how u did it but as far as i can say you are the master

**Comment by ibnumalik** [comment]
thanks @mdomnita you the real mvp

**Comment by h4ck-rOOt** [comment]
After the code rewrite this issue should be fixed.
